### ISSUE TITLE
Show amp

### ISSUE THREAD

**Issue by lindajk** [lindajk/capstone-project#1]
## Value proposition

**As a** user,
**I want to** see a map,
**so that** I can see my city in the map.

## Description

![Show map](https://user-images.githubusercontent.com/104507734/175255675-ad8d513d-4596-492d-bd84-f2004862b914.png)

## Acceptance criteria

- [ ] Map-API is accessible
- [ ] Map is displayed 
- [ ] Map can be zoomed in and out

## Complexity

Medium

## Tasks

- [ ] Create branch
- [ ] Define size
- [ ] Implement map component
- [ ] Fetch API
- [ ] Implement zoom feature
- [ ] Write specs for map component
