### ISSUE TITLE
Show event location

### ISSUE THREAD

**Issue by lindajk** [lindajk/capstone-project#2]
## Value proposition

**As a** user,
**I want to** see event locations on the map,
**so that** I know where events take place in my city.

## Description

![Show event location](https://user-images.githubusercontent.com/104507734/175261256-cf45d5ad-c7db-4f68-9bef-4e7423ffab66.png)

## Acceptance criteria

- Event-API is accessible
- Event location is displayed on the map at the right location
- Event location name is displayed on the map 

## Complexity

Large

## Tasks

- [ ] Create branch
- [ ] Style location icon
- [ ] Implement event location component
- [ ] Fetch API
- [ ] Map event location to the map
- [ ] Display event location icon
- [ ] Display event location name
- [ ] Write specs for event location component
