### ISSUE TITLE
Show event in list

### ISSUE THREAD

**Issue by lindajk** [lindajk/capstone-project#3]
## Value proposition

**As a** user,
**I want to** see events in a list,
**so that** I know which event takes place. 

## Description

![Show event in list](https://user-images.githubusercontent.com/104507734/175280368-1a495e97-7fd7-4be2-8263-b23d9a55cc38.png)

## Acceptance criteria

- [ ] Events are fetched from API
- [ ] List of events is vertically scrollable

## Complexity

Medium

## Tasks

- [ ] Create branch
- [ ] Add base styles
- [ ] Setup Storybook for EventList
- [ ] Create EventList component
- [ ] Create array for EventList component
- [ ] Fetch events from API
- [ ] Display events in array
- [ ] Add EventList to App
- [ ] Render events in an unordered list

**Comment by ahohnsen** [comment]
Hey Linda,

Nice work! 

As your data is fetched from an API, you should also show an error message if there is an error while fetching. So I would suggest to add an additional scribble to show how that would look like and add this to the acceptance criteria.

**Comment by lindajk** [comment]
> Hey Linda,
> 
> Nice work!
> 
> As your data is fetched from an API, you should also show an error message if there is an error while fetching. So I would suggest to add an additional scribble to show how that would look like and add this to the acceptance criteria.

Done!
