### ISSUE TITLE
Filter events in list by city

### ISSUE THREAD

**Issue by lindajk** [lindajk/capstone-project#4]
## Value proposition

**As a** user,
**I want to** ...
**so that** ...

## Description

![Filter event in list by city](https://user-images.githubusercontent.com/104507734/175281870-7602ef92-d6fc-4452-b8b6-58179844f98c.png)
![Filter event in list by city - dropdown](https://user-images.githubusercontent.com/104507734/175284077-c0fbc4fa-12e9-4d04-b70f-efeb18720ce7.png)
![Filter event in list by city - chosen city](https://user-images.githubusercontent.com/104507734/175284094-e36d3f4d-48ca-4c0b-829f-85c8341275a0.png)

## Acceptance criteria

- [ ] Dropdown menu pops up when clicking on City button
- [ ] I can choose a city from dropdown menu
- [ ] Chosen city is displayed in a list

## Complexity

Medium to Large

## Tasks

- [ ] Create branch
- [ ] Add City button
- [ ] Setup Storybook for CityButton
- [ ] Create CityButton component
- [ ] Add filter function
- [ ] Write specs for CityButton
- [ ] Add CityButton to App
