### ISSUE TITLE
3. Event list by date

### ISSUE THREAD

**Issue by lindajk** [lindajk/capstone-project#5]
## Value proposition

**As a** user,
**I want to** choose a date,
**so that** I can see all events on the chosen date.

## Description

![Event list by date](https://user-images.githubusercontent.com/104507734/175512042-4b7fe573-bd66-441b-9e7c-0b2da9b92bce.png)

## Acceptance criteria

- [x] Events on chosen date is vertically scrollable
- [x] Date button is on right top and sticky

## Complexity

Medium

## Tasks

- [x] Create branch
- [x] Add DateButton
- [x] Setup Storybook for DateButton
- [x] Create DateButton component
- [x] Add filter function
- [x] Write specs for DateButton
- [x] Add DateButton to App

**Comment by lindajk** [comment]
> Hi Linda,
> I like your user story! 👍 You rock! 🪨 I only have one question:
> If your events are filtered by day, is there a specific sorting of these events for each day? For example, by time or by name? I would be interested in that and that would also be a detail that you could include in the acceptance criteria.

Hi Mareike, 
thank you for reviewing my story! Indeed I didn't think about the sorting order. 
Now I have added to my very first user story (where the event list is fetched from the API and rendered for the first time) that the event list will be sorted by date and time in ascending order! :)
