### ISSUE TITLE
Event list by category

### ISSUE THREAD

**Issue by lindajk** [lindajk/capstone-project#6]
## Value proposition

**As a** user,
**I want to** choose a category, 
**so that** I can see all events in the chosen category.

## Description

![Event list by category](https://user-images.githubusercontent.com/104507734/175309029-40280227-08dd-4b0e-98c5-a6783ca1a141.png)

## Acceptance criteria

-  [ ] Events in chosen category is displayed in a list
-  [ ] Category bar is sticky but horizontally scrollable 

## Complexity

Medium to Large

## Tasks

- [ ] Create branch
- [ ] Add Category buttons
- [ ] Setup Storybook for CategoryButton
- [ ] Create CategoryButton component
- [ ] Make CategoryBar scrollable
- [ ] Write specs for CategoryBar
- [ ] Add CategoryBar to App
